# Generated by Django 5.2.6 on 2025-09-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('stock', '0002_remove_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
    ]
